### ISSUE TITLE
"Error: An invalid exception was thrown." when mousing over

### ISSUE THREAD

**Issue by dandv** [zeroclipboard/zeroclipboard#589] opened 2015-07-08 01:07 UTC
This might be a general case of #570. Further docs reading points out it's a [cross-protocol limitation](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#cross-protocol-limitations). Thought I'd create this issue for others who run into the same problem. TL;DR: serve the library and the script that uses it *both* from `http` or `https` origins. I had loaded ZC from CDNJS over `https`, thinking https resources scripted from an http origin would be okay. It's not :)

Compare http://idorecall.com/zero-clipboard.html to https://idorecall.com/zero-clipboard.html.

Over http, when I mouse over the button, the Chrome console displays `Error: An invalid exception was thrown.` for the line `var result = swfCallback.apply(this, args);` in the VM.

Here is the full code:

```html
<html>
  <body>
    <button id="copy-button" data-clipboard-text="Copy Me!" title="Click to copy me.">Copy to Clipboard</button>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        var client = new ZeroClipboard( document.getElementById("copy-button") );
    
        client.on( "ready", function( readyEvent ) {
          // alert( "ZeroClipboard SWF is ready!" );
    
          client.on( "aftercopy", function( event ) {
            // `this` === `client`
            // `event.target` === the element that was clicked
            event.target.style.display = "none";
            alert("Copied text to clipboard: " + event.data["text/plain"] );
          });  
        } );
      } );
    </script>
  </body>
</html>
```

Not sure if this merits additional documentation. Maybe I'm just doomed to keep running into all [sorts](https://github.com/zeroclipboard/zeroclipboard/issues/588) of [snags](https://github.com/zeroclipboard/zeroclipboard/pull/586).

**Comment by iDuuck** [comment] 2015-07-31 12:27
Try changing the `https://` of the CloudFlare CDN to `//` so that it loads the protocol that it needs. Without `https` it works flawless for me.
It should look like this:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js"></script>
```

**Comment by JamesMGreene** [comment] 2015-08-27 11:07
:+1: to @iDuuck's comment.

Additionally, I am going to add YAEE (yet another `error` event) in the next release: `error[name = "flash-insecure"]`. See #532 for more info on that.

In that regard, I am going to consider this a duplicate of #532.

**Closed by JamesMGreene** 2015-08-27 11:07 UTC
Labels: duplicate

**Comment by valeriisukhov** [comment] 2016-05-27 12:10
Got this issue in Chrome 51, CDN is "//"

**Comment by JamesMGreene** [comment] 2016-05-27 17:01
@valeriisukhov Are you using CDNJS? If so, see #632.

**Comment by valeriisukhov** [comment] 2016-05-30 11:06
@JamesMGreene many thanks! All seems fine now!
