### ISSUE TITLE
Google Chrome Version 44 und 45 copy no Carriage Return

### ISSUE THREAD

**Issue by shining01** [zeroclipboard/zeroclipboard#610] opened 2015-09-08 11:36 UTC
Hello,

 i have testet with http://zeroclipboard.org/ Demo page on Windows 10. If i type text and then press enter and copy paste it, ZeroClipboard insert no Carriage Return in e.g. Microsoft editor. All lines are in the same row.
The new Internet Explorer "Edge" works well.

**Comment by JamesMGreene** [comment] 2015-09-08 23:43
Duplicate of #595. Already fixed in the current `master` branch but not yet released.

**Closed by JamesMGreene** 2015-09-08 23:43 UTC
