### ISSUE TITLE
No data copied when string contains %

### ISSUE THREAD

**Issue by nuxsmin** [zeroclipboard/zeroclipboard#594] opened 2015-07-25 16:18 UTC
Hi, great work and a very useful application!!

I've an issue with % characters as they have not being copied to the clipboard. I've tested it on demo page and after that the swf movie seems to be gone.

I there any issue about it?

Kind regards.

**Comment by JamesMGreene** [comment] 2015-08-27 14:12
I'm going to consider this a duplicate of #565.

**Closed by JamesMGreene** 2015-08-27 14:12 UTC
Labels: bug, duplicate, Flash, major
