### ISSUE TITLE
cannot use on mobile?

### ISSUE THREAD

**Issue by douglasvegas** [zeroclipboard/zeroclipboard#659] opened 2016-07-21 09:06 UTC
I can copy the text  on the PC,but it doesnt work on mobile...
How to make it works on mobile?

**Comment by Spocher** [comment] 2016-07-31 17:29
Join us. On mobile devices is not working. Is it possible to do this?

**Comment by douglasvegas** [comment] 2016-09-02 06:06
It seems it has no permission to do this.

**Comment by JamesMGreene** [comment] 2016-10-27 11:34
ZeroClipboard as it stands today will only work if Flash is available. Once we get #171 and its corresponding PR taken care of, that will add some support for mobile browsers that support the HTML5 Clipboard API as well.

Closing as duplicate of #171. Please subscribe to that issue instead for updates.

**Closed by JamesMGreene** 2016-10-27 11:34 UTC
Labels: duplicate
