### ISSUE TITLE
Multiple clipboard targets do not seem to work

### ISSUE THREAD

**Issue by gitgrimbo** [zeroclipboard/zeroclipboard#585] opened 2015-06-29 19:28 UTC
http://fiddle.jshell.net/fiddlegrimbo/b13L4ktL/4/show/

Steps to reproduce:

- Position the mouse pointer beneath the "6" element.  E.g. over the "Z" in the **ZeroClipboard state** heading.
- Refresh the page. Ctrl+R.
- Move mouse slowly up the page to hover over "6".
- "6" should be 'copyable',
- Move mouse slowly up the page to hover over "5".
- "5" is not copyable.
- Moving up the page some more will give "4" and "2" as copyable, and "3" and "1" as not copyable.

Yet if you then continue to move the mouse up the page above JSFiddle's "Result" heading, and then start to move the mouse back down again, each item ("1" to "6") is copyable.

But if you move the mouse up and down across the elements, only "6", "4" and "2" remain as copyable and you can make the other items lose their 'copyability'.

- Win 7
- Reproduced in Chrome 43.0.2357.130 m.
- Not reproduced in Firefox 38.0.5.

````
{
  "browser": {
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36",
    "platform": "Win32",
    "appName": "Netscape"
  },
  "flash": {
    "version": "18.0.0",
    "pluginType": "pepper",
    "disabled": false,
    "outdated": false,
    "sandboxed": false,
    "unavailable": null,
    "degraded": null,
    "deactivated": null,
    "overdue": false,
    "ready": false
  },
  "zeroclipboard": {
    "version": "2.2.0",
    "config": {
      "swfPath": "http://rawgit.com/zeroclipboard/zeroclipboard/master/dist/ZeroClipboard.swf",
      "trustedDomains": [
        "fiddle.jshell.net"
      ],
      "cacheBust": true,
      "forceEnhancedClipboard": false,
      "flashLoadTimeout": 30000,
      "autoActivate": true,
      "bubbleEvents": true,
      "containerId": "global-zeroclipboard-html-bridge",
      "containerClass": "global-zeroclipboard-container",
      "swfObjectId": "global-zeroclipboard-flash-bridge",
      "hoverClass": "zeroclipboard-is-hover",
      "activeClass": "zeroclipboard-is-active",
      "forceHandCursor": true,
      "title": null,
      "zIndex": 999999999
    }
  }
}
````

**Comment by JamesMGreene** [comment] 2015-08-27 14:19
I know one is very frustrating but it is also proving difficult to fix 100%.

Duplicate of #463.  There are some possibly acceptable workarounds for the short-term mentioned in that issue as well, primarily providing more vertical space as a buffer between elements.

**Closed by JamesMGreene** 2015-08-27 14:19 UTC
