### ISSUE TITLE
Will the Chrome flash-block announcement have any impact on ZeroClipboard?

### ISSUE THREAD

**Issue by arxpoetica** [zeroclipboard/zeroclipboard#606] opened 2015-08-28 14:31 UTC
See: https://plus.google.com/+GoogleAds/posts/2PmwKinJ7nj for more info
Also: https://news.ycombinator.com/item?id=10133771 (sub discussion: https://news.ycombinator.com/item?id=10133915)

**Comment by cpeterso** [comment] 2015-08-28 18:29
This is a duplicate of issue #171.

**Closed** 2015-08-29 14:05 UTC
